### ISSUE TITLE
bench test segfault on armhf

### ISSUE THREAD

**Issue by seb128** [FFTW/fftw3#182]
The 3.3.8 armhf build currently fails on Ubuntu due to a test segfault

Build log
https://launchpadlibrarian.net/445790519/buildlog_ubuntu-eoan-armhf.fftw3_3.3.8-2_BUILDING.txt.gz

==5906== Command: ./bench --verify ofr108*118
==5906==
==5906== Invalid write of size 8
==5906== at 0x49174A8: vst1_f32 (arm_neon.h:10876)
==5906== by 0x49174A8: ST (simd-neon.h:119)
==5906== by 0x49174A8: n1fv_9 (n1fv_9.c:230)
==5906== by 0x4884F4F: dobatch (direct.c:51)
==5906== by 0x48850B5: apply_buf (direct.c:87)
==5906== by 0x48869B1: fftwf_dft_solve (solve.c:29)
==5906== by 0x4882407: measure (timer.c:136)
==5906== by 0x4882407: fftwf_measure_execution_time (timer.c:159)
==5906== by 0x4880725: evaluate_plan (planner.c:460)
==5906== by 0x48808B9: search0 (planner.c:529)
==5906== by 0x48809B1: search (planner.c:600)
==5906== by 0x48809B1: mkplan (planner.c:711)
==5906== by 0x4880D2D: fftwf_mkplan_d (planner.c:970)
==5906== by 0x48B5A0F: mkplan (ct-hc2c.c:198)
==5906== by 0x48807E3: invoke_solver (planner.c:486)
==5906== by 0x48807E3: search0 (planner.c:529)
==5906== by 0x48809B1: search (planner.c:600)
==5906== by 0x48809B1: mkplan (planner.c:711)
==5906== Address 0x96bafa8 is not stack'd, malloc'd or (recently) free'd
==5906==
==5906==
==5906== Process terminating with default action of signal 11 (SIGSEGV)
==5906== Access not within mapped region at address 0x96BAFA8
==5906== at 0x49174A8: vst1_f32 (arm_neon.h:10876)
==5906== by 0x49174A8: ST (simd-neon.h:119)
==5906== by 0x49174A8: n1fv_9 (n1fv_9.c:230)
==5906== by 0x4884F4F: dobatch (direct.c:51)
==5906== by 0x48850B5: apply_buf (direct.c:87)
==5906== by 0x48869B1: fftwf_dft_solve (solve.c:29)
==5906== by 0x4882407: measure (timer.c:136)
==5906== by 0x4882407: fftwf_measure_execution_time (timer.c:159)
==5906== by 0x4880725: evaluate_plan (planner.c:460)
==5906== by 0x48808B9: search0 (planner.c:529)
==5906== by 0x48809B1: search (planner.c:600)
==5906== by 0x48809B1: mkplan (planner.c:711)
==5906== by 0x4880D2D: fftwf_mkplan_d (planner.c:970)
==5906== by 0x48B5A0F: mkplan (ct-hc2c.c:198)
==5906== by 0x48807E3: invoke_solver (planner.c:486)
==5906== by 0x48807E3: search0 (planner.c:529)
==5906== by 0x48809B1: search (planner.c:600)
==5906== by 0x48809B1: mkplan (planner.c:711)

**Comment by vanvugt** [comment]
Looks like a duplicate of #30 ?

**Comment by drmpeg** [comment]
Here's a gdb backtrace.
```
Core was generated by `/usr/bin/python3 -u /home/ubuntu/xfer/vv009_4kfft.py'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xb04cdac2 in vst1_f32 (__b=..., __a=0x4fad790)
    at /usr/local/lib/gcc/arm-linux-gnueabihf/10/include/arm_neon.h:10880
10880	  __builtin_neon_vst1v2sf ((__builtin_neon_sf *) __a, __b);
[Current thread is 1 (Thread 0xb6efd460 (LWP 18404))]
#0  0xb04cdac2 in vst1_f32 (__b=..., __a=0x4fad790)
    at /usr/local/lib/gcc/arm-linux-gnueabihf/10/include/arm_neon.h:10880
#1  ST (aligned_like=<optimized out>, ovs=<optimized out>, v=..., x=0x4fad690)
    at ../../../simd-support/simd-neon.h:119
#2  n1bv_32 (ri=<optimized out>, ii=<optimized out>, ro=<optimized out>, 
    io=<optimized out>, is=<optimized out>, os=2, v=16, ivs=64, ovs=64)
    at ../common/n1bv_32.c:676
#3  0xb042d1b6 in apply (ego_=<optimized out>, ri=<optimized out>, 
    ii=<optimized out>, ro=<optimized out>, io=0x27d6ad0) at direct.c:96
#4  0xb042ed5e in fftwf_dft_solve (ego_=<optimized out>, p_=<optimized out>)
    at solve.c:29
#5  0xb042a3a4 in measure (iter=<optimized out>, p=<optimized out>, 
    pln=<optimized out>) at timer.c:136
#6  fftwf_measure_execution_time (plnr=plnr@entry=0x21f44a0, 
    pln=pln@entry=0x2753a40, p=p@entry=0x2800c80) at timer.c:159
#7  0xb0427ff8 in evaluate_plan (ego=0x21f44a0, pln=0x2753a40, p=0x2800c80)
    at planner.c:460
#8  0xb04281a2 in search0 (ego=ego@entry=0x21f44a0, p=p@entry=0x2800c80, 
    slvndx=slvndx@entry=0xbea504f8, flagsp=flagsp@entry=0xbea504fc)
    at planner.c:529
#9  0xb04282ca in search (flagsp=0xbea504fc, slvndx=0xbea504f8, p=0x2800c80, 
    ego=0x21f44a0) at planner.c:600
#10 mkplan (ego=0x21f44a0, p=0x2800c80) at planner.c:711
#11 0xb04286b2 in fftwf_mkplan_d (ego=ego@entry=0x21f44a0, p=0x2800c80)
    at planner.c:970
#12 0xb042bf72 in mkplan (plnr=0x21f44a0, p_=0x2800be0, ego_=<optimized out>)
    at ct.c:154
#13 mkplan (ego_=<optimized out>, p_=0x2800be0, plnr=0x21f44a0) at ct.c:119
#14 0xb04280cc in invoke_solver (nflags=<optimized out>, s=<optimized out>, 
    p=0x2800be0, ego=0x21f44a0) at planner.c:486
#15 search0 (ego=ego@entry=0x21f44a0, p=p@entry=0x2800be0, 
    slvndx=slvndx@entry=0xbea50648, flagsp=flagsp@entry=0xbea5064c)
    at planner.c:529
#16 0xb04282ca in search (flagsp=0xbea5064c, slvndx=0xbea50648, p=0x2800be0, 
    ego=0x21f44a0) at planner.c:600
#17 mkplan (ego=0x21f44a0, p=0x2800be0) at planner.c:711
#18 0xb04286b2 in fftwf_mkplan_d (ego=ego@entry=0x21f44a0, p=0x2800be0)
    at planner.c:970
#19 0xb042eea2 in mkplan (ego_=0x27f6f68, p_=0x2800c00, plnr=0x21f44a0)
    at vrank-geq1.c:165
#20 0xb04280cc in invoke_solver (nflags=<optimized out>, s=<optimized out>, 
    p=0x2800c00, ego=0x21f44a0) at planner.c:486
#21 search0 (ego=ego@entry=0x21f44a0, p=p@entry=0x2800c00, 
    slvndx=slvndx@entry=0xbea50760, flagsp=flagsp@entry=0xbea50764)
    at planner.c:529
#22 0xb04282ca in search (flagsp=0xbea50764, slvndx=0xbea50760, p=0x2800c00, 
    ego=0x21f44a0) at planner.c:600
#23 mkplan (ego=0x21f44a0, p=0x2800c00) at planner.c:711
#24 0xb04286b2 in fftwf_mkplan_d (ego=ego@entry=0x21f44a0, p=0x2800c00)
    at planner.c:970
#25 0xb042bf72 in mkplan (plnr=0x21f44a0, p_=0x2800b90, ego_=<optimized out>)
    at ct.c:154
#26 mkplan (ego_=<optimized out>, p_=0x2800b90, plnr=0x21f44a0) at ct.c:119
#27 0xb04280cc in invoke_solver (nflags=<optimized out>, s=<optimized out>, 
    p=0x2800b90, ego=0x21f44a0) at planner.c:486
#28 search0 (ego=ego@entry=0x21f44a0, p=p@entry=0x2800b90, 
    slvndx=slvndx@entry=0xbea508b0, flagsp=flagsp@entry=0xbea508b4)
    at planner.c:529
#29 0xb04282ca in search (flagsp=0xbea508b4, slvndx=0xbea508b0, p=0x2800b90, 
    ego=0x21f44a0) at planner.c:600
#30 mkplan (ego=0x21f44a0, p=0x2800b90) at planner.c:711
#31 0xb04b6fb0 in mkplan0 (wisdom_state=WISDOM_NORMAL, hash_info=0, 
    prb=0x2800b90, flags=0, plnr=0x21f44a0) at apiplan.c:42
#32 mkplan (hash_info=0, prb=0x2800b90, flags=0, plnr=0x21f44a0)
    at apiplan.c:56
#33 fftwf_mkapiplan (sign=sign@entry=1, flags=flags@entry=0, prb=0x2800b90)
    at apiplan.c:124
#34 0xb04ba062 in fftwf_plan_many_dft (rank=rank@entry=1, 
    n=n@entry=0xbea509fc, howmany=howmany@entry=1, in=0x27b6aa0, 
    inembed=inembed@entry=0x0, istride=istride@entry=1, idist=idist@entry=1, 
    out=0x27d6ad0, onembed=onembed@entry=0x0, ostride=ostride@entry=1, 
    odist=odist@entry=1, sign=sign@entry=1, flags=flags@entry=0)
    at plan-many-dft.c:40
#35 0xb04b9b42 in fftwf_plan_dft (rank=rank@entry=1, n=n@entry=0xbea509fc, 
    in=<optimized out>, out=<optimized out>, sign=sign@entry=1, 
    flags=flags@entry=0) at plan-dft.c:26
#36 0xb04b99ce in fftwf_plan_dft_1d (n=<optimized out>, n@entry=16384, 
    in=<optimized out>, out=<optimized out>, sign=sign@entry=1, 
    flags=flags@entry=0) at plan-dft-1d.c:26
#37 0xb07fe344 in gr::fft::fft_complex::fft_complex (this=0xa78fd2dc, 
    fft_size=16384, forward=<optimized out>, nthreads=1)
    at /usr/local/include/c++/10/bits/stl_vector.h:1168
#38 0xaf8de04e in gr::dtv::dvbt2_pilotgenerator_cc_impl::dvbt2_pilotgenerator_cc_impl (this=this@entry=0xa7869008, 
    carriermode=carriermode@entry=gr::dtv::CARRIERS_EXTENDED, 
    fftsize=fftsize@entry=gr::dtv::FFTSIZE_16K, 
    pilotpattern=pilotpattern@entry=gr::dtv::PILOT_PP4, 
    guardinterval=guardinterval@entry=gr::dtv::GI_1_32, 
    numdatasyms=numdatasyms@entry=83, 
    paprmode=paprmode@entry=gr::dtv::PAPR_OFF, 
    version=version@entry=gr::dtv::VERSION_111, 
    preamble=preamble@entry=gr::dtv::PREAMBLE_T2_SISO, 
    misogroup=misogroup@entry=gr::dtv::MISO_TX1, 
    equalization=equalization@entry=gr::dtv::EQUALIZATION_OFF, 
    bandwidth=bandwidth@entry=gr::dtv::BANDWIDTH_8_0_MHZ, 
    vlength=vlength@entry=16384, __in_chrg=<optimized out>, 
    __vtt_parm=<optimized out>)
    at /usr/local/include/c++/10/bits/stl_vector.h:97
#39 0xaf8dfc36 in gr::dtv::dvbt2_pilotgenerator_cc::make (
    carriermode=carriermode@entry=gr::dtv::CARRIERS_EXTENDED, 
    fftsize=fftsize@entry=gr::dtv::FFTSIZE_16K, 
    pilotpattern=pilotpattern@entry=gr::dtv::PILOT_PP4, 
    guardinterval=guardinterval@entry=gr::dtv::GI_1_32, 
    numdatasyms=numdatasyms@entry=83, 
    paprmode=paprmode@entry=gr::dtv::PAPR_OFF, 
    version=version@entry=gr::dtv::VERSION_111, 
    preamble=preamble@entry=gr::dtv::PREAMBLE_T2_SISO, 
    misogroup=misogroup@entry=gr::dtv::MISO_TX1, 
    equalization=equalization@entry=gr::dtv::EQUALIZATION_OFF, 
    bandwidth=bandwidth@entry=gr::dtv::BANDWIDTH_8_0_MHZ, 
    vlength=vlength@entry=16384)
    at /home/ubuntu/xfer/gnuradio/gr-dtv/lib/dvbt2/dvbt2_pilotgenerator_cc_impl.cc:35
#40 0xad75ca94 in _wrap_dvbt2_pilotgenerator_cc_make (args=<optimized out>, 
    kwargs=<optimized out>)
    at /home/ubuntu/xfer/gnuradio/build/gr-dtv/swig/CMakeFiles/dtv_swig1.dir/dtv_swig1PYTHON_wrap.cxx:6195
#41 0x0015ec6c in PyCFunction_Call ()
#42 0x0015f664 in _PyObject_MakeTpCall ()
#43 0x000dfd9a in _PyEval_EvalFrameDefault ()
#44 0xaeadd35c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by svillemot** [comment]
Note that this bug also hit Debian at some point, but is now fixed. This most likely means that the bug was in the toolchain, and has been fixed lately. For more details: https://bugs.debian.org/943396

**Comment by vanvugt** [comment]
Yeah my proposed fix (which didn't land in Debian but did in Ubuntu) also suggests it was the toolchain: https://salsa.debian.org/science-team/fftw3/-/merge_requests/1/diffs
