### ISSUE TITLE
AddressSanitizer reports memory leaks when calling fftw_alloc_real

### ISSUE THREAD

**Issue by marioortizmanero** [FFTW/fftw3#186]
AddressSanitizer output:

```
Direct leak of 112 byte(s) in 1 object(s) allocated from:
    #0 0x7fe875aab316 in __interceptor_memalign /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:169
    #1 0x55616de9b2b6 in cross_correlation ../src/cross_correlation.c:72
    #2 0x55616de9ae6c in main /home/mario/Programming/audiosync/tests/tests.c:35
    #3 0x7fe8748ff152 in __libc_start_main (/usr/lib/libc.so.6+0x27152)
```
Where `cross_correlation ../src/cross_correlation.c:72` is:

```c
double *data1 = fftw_alloc_real(length);
```

Length is just a `size_t length = ...` with a variable value, usually between 144000 and 720000.

I'm using the latest FFTW release (3.3.8-1) on Arch Linux.

**Comment by marioortizmanero** [comment]
This was my own mistake sorry. Closing it.
